// Auto-generated by deployment script
export const PACKAGE_ID = '0x...' // Will be updated after deployment
export const ORACLE_CAP_ID = '0x...' // Oracle authority
export const NETWORK = 'testnet'

// Game Configuration
export const GAME_CONFIG = {
  TANK_MINT_FEE: 0, // Free tank minting
  GUN_MINT_FEE: 100_000_000, // 0.1 SUI in MIST
  MARKETPLACE_FEE_PERCENT: 5, // 5% marketplace fee
  GUN_RARITY: {
    NAMES: ['Common', 'Rare', 'Epic', 'Legendary'],
    COLORS: ['#9CA3AF', '#3B82F6', '#8B5CF6', '#F59E0B']
  },
  BATTLE: {
    MAX_DURATION: 600000, // 10 minutes
    MAX_DAMAGE: 1000,
    WINNER_REWARD_PERCENTAGE: 90,
    HOUSE_FEE_PERCENTAGE: 10
  }
}

// Oracle Configuration
export const ORACLE_CONFIG = {
  WEBSOCKET_URL: 'ws://localhost:8080',
  GUN_ECONOMY_API: 'http://localhost:3001',
  VALIDATION_RULES: {
    MAX_SPEED: 100,           // pixels/second
    MIN_FIRE_INTERVAL: 500,   // milliseconds
    MAX_TELEPORT_DISTANCE: 200, // pixels
    MAX_BATTLE_DURATION: 600000 // milliseconds
  }
}

// Contract Object IDs (updated after deployment)
export const OBJECT_IDS = {
  MARKETPLACE_ID: '0x...',
  MARKET_DATA_ID: '0x...',
  GAME_STATE_ID: '0x...',
  MATCHMAKING_POOL_ID: '0x...',
  LEADERBOARD_ID: '0x...'
}