#!/usr/bin/env node
import { execSync } from 'child_process'
import { writeFileSync } from 'fs'

class ContractDeployer {
  async deployToTestnet() {
    console.log('🚀 Deploying Move contracts to Sui Testnet...')
    
    try {
      // Build contracts
      execSync('cd move_contracts && sui move build', { stdio: 'inherit' })
      
      // Deploy to testnet
      const deployResult = execSync('cd move_contracts && sui client publish --gas-budget 100000000', { encoding: 'utf8' })
      
      // Extract package ID and object IDs from deployment result
      const packageIdMatch = deployResult.match(/Package ID: (0x[a-fA-F0-9]+)/)
      const oracleCapMatch = deployResult.match(/OracleCap.*ID: (0x[a-fA-F0-9]+)/)
      
      if (packageIdMatch) {
        const packageId = packageIdMatch[1]
        const oracleCapId = oracleCapMatch ? oracleCapMatch[1] : '0x...'
        
        // Update SDK with deployment info
        const sdkContent = `// Auto-generated by deployment script
export const PACKAGE_ID = '${packageId}'
export const ORACLE_CAP_ID = '${oracleCapId}'
export const NETWORK = 'testnet'

// Contract modules:
// - ${packageId}::game (Tank NFTs)
// - ${packageId}::battle (PvP settlement)
// - ${packageId}::token (TANK_TOKEN)
// - ${packageId}::treasury (staking)
// - ${packageId}::leaderboard (rankings)
// - ${packageId}::matchmaking (auto-match)`
        
        writeFileSync('frontend/src/sdk/constants.ts', sdkContent)
        
        console.log(`✅ Smart contracts deployed successfully!`)
        console.log(`📦 Package ID: ${packageId}`)
        console.log(`🔑 Oracle Cap ID: ${oracleCapId}`)
        console.log(`🎯 Architecture: On-chain settlement + Off-chain gameplay`)
      }
      
    } catch (error) {
      console.error('❌ Deployment failed:', error)
      process.exit(1)
    }
  }
}

new ContractDeployer().deployToTestnet()